import Head from "next/head";
import styles from "../styles/Home.module.css";
import { getProductsInCollection } from "../lib/shopify";
import Products from "../components/Products";
import HeroSection from './../components/HeroSection';

export default function Home({ products }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Serif Colakel Shopify - with NextJS TailwindCSS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <HeroSection />
        <Products products={products} />
      </main>

    </div>
  );
}

export async function getStaticProps() {
  const products = await getProductsInCollection();
  return {
    props: { products },
  };
}
