import Head from "next/head";
import styles from "../styles/Home.module.css";
import { getProductsInCollection } from "../lib/shopify";
import Products from "../components/Products";
export default function Home({ products }) {
  console.log("products", products);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <Products products={products} />
      </main>

    </div>
  );
}

export async function getStaticProps() {
  const products = await getProductsInCollection();
  return {
    props: { products },
  };
}
